name: machine_test_norq
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  badges: ^3.1.2
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  dio: ^5.4.1
  sqflite: ^2.3.2
  path: ^1.8.3
  lottie: ^3.1.0
  firebase_auth: ^4.17.5
  firebase_core: ^2.23.0
  get_storage: ^2.1.1

dev_dependencies: 
  flutter_lints: 3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
  
  fonts:
   - family: Poppins
     fonts:
       - asset: assets/fonts/Poppins-Regular.ttf

